//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactAllowListEntry) DeepCopyInto(out *ArtifactAllowListEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactAllowListEntry.
func (in *ArtifactAllowListEntry) DeepCopy() *ArtifactAllowListEntry {
	if in == nil {
		return nil
	}
	out := new(ArtifactAllowListEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGatePolicy) DeepCopyInto(out *ModelGatePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGatePolicy.
func (in *ModelGatePolicy) DeepCopy() *ModelGatePolicy {
	if in == nil {
		return nil
	}
	out := new(ModelGatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelGatePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGatePolicyList) DeepCopyInto(out *ModelGatePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelGatePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGatePolicyList.
func (in *ModelGatePolicyList) DeepCopy() *ModelGatePolicyList {
	if in == nil {
		return nil
	}
	out := new(ModelGatePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelGatePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGatePolicySpec) DeepCopyInto(out *ModelGatePolicySpec) {
	*out = *in
	if in.ArtifactAllowList != nil {
		in, out := &in.ArtifactAllowList, &out.ArtifactAllowList
		*out = make([]ArtifactAllowListEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGatePolicySpec.
func (in *ModelGatePolicySpec) DeepCopy() *ModelGatePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ModelGatePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelGatePolicyStatus) DeepCopyInto(out *ModelGatePolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelGatePolicyStatus.
func (in *ModelGatePolicyStatus) DeepCopy() *ModelGatePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ModelGatePolicyStatus)
	in.DeepCopyInto(out)
	return out
}
